# Generated by Django 3.0.5 on 2020-04-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0003_auto_20200407_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='process_number',
        ),
    ]
